<<<<<<< HEAD
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

=======
# Azure DevOps pipeline for Node.js Express server
>>>>>>> 30f2d04 (Add Azure DevOps pipeline with artifacts)
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
<<<<<<< HEAD
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
=======
  displayName: Install Node.js
  inputs:
    versionSpec: '20.x'
>>>>>>> 30f2d04 (Add Azure DevOps pipeline with artifacts)

- script: |
    npm install
    npm run build
<<<<<<< HEAD
  displayName: 'npm install and build'

- task: CopyFiles@2
=======
  displayName: npm install and build

- task: CopyFiles@2
  displayName: Copy files to artifact staging
>>>>>>> 30f2d04 (Add Azure DevOps pipeline with artifacts)
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/*
<<<<<<< HEAD
      !node_modules/**
      !.git/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
=======
      !node_modules/**/*
      !.git/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    publishLocation: Container
>>>>>>> 30f2d04 (Add Azure DevOps pipeline with artifacts)
